version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # Use target to specify which stage to use for development
      target: builder
    ports:
      - "3000:3000"
    # For development mode, we'll use these volumes
    # In production, you would use the final image without these volumes
    volumes:
      - ./frontend:/app
      # Prevent node_modules from being overwritten by the host volume
      - /app/node_modules
      # Prevent .next from being overwritten
      - /app/.next
    environment:
      NODE_ENV: development
      # Prevent Next.js from opening a browser
      BROWSER: none
      # Enable polling for file changes in Docker
      WATCHPACK_POLLING: true
      # Disable telemetry for Next.js
      NEXT_TELEMETRY_DISABLED: 1
    # Override CMD in Dockerfile to run in development mode with hot-reloading
    command: npm run dev
